README.md, down.sh, up.sh
1. Register the deployments into ./.bootstrap/bootstrapped-deployments during up.sh
2. Read from ./.bootstrap/bootstrapped-deployments during down.sh
3. Added printouts to test if an error has occurred (?$)
4. Added printout of the docker-compose command as I use it very often and since here it's complicated due to many directories I thought printing it to the user would be useful.
(Example: `docker-compose -f deployments/tyk/docker-compose.yml -f deployments/sso/docker-compose.yml -f deployments/tls/docker-compose.yml -p tyk-pro-docker-demo-extended --project-directory /Users/yaara/work/src/github.com/TykTechnologies/tyk-demo ps`)
5. Have updated the README accordingly
6. Added `--remove-orphanes` to remove containers for services not defined in the Compose file.
=> Remove the requirement of down.sh for arguments

README.md, deployments/tyk/bootstrap.sh, deployments/tyk/data/tyk-dashboard/organisation.json, deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf, scripts/export.sh, scripts/import.sh
Portal now bound to `tyk-portal.localhost:3000`, and accessible through http://tyk-portal.localhost:3000/portal
=> Portal fix

deployments/analytics/docker-compose.yml, deployments/analytics/volumes/tyk-pump/pump-elasticsearch.conf, deployments/mdcb/docker-compose.yml, deployments/sso/docker-compose.yml, deployments/tyk/docker-compose.yml, deployments/tyk/volumes/tyk-pump/pump.conf, deployments/tyk2/docker-compose.yml, deployments/tyk2/volumes/tyk-pump/pump.conf
1) Pins the component versions to most recent release.
Leaving TiB as "latest" tag because the last stable release is ancient (`0.7.0`)
2) Fixing pump.conf.  The values in pump.conf were in. the wrong place for Aggregate pump and removed a value that doesn't exist for selective pump.
Will now correctly display analytics in the Portal Dashboard:
=> pin component versions and fix pump confs

README.md, deployments/tyk/docker-compose.yml
1. Remove env var from docker-compose since it's enough to refer to the .env file in the docker-compose and define the env vars in the .env file. 
2. Expose the pump's health check port so you can test it outside the network
=> Use .env instead of env vars and expost pump's healthcheck port

deployments/mdcb/docker-compose.yml, deployments/sso/docker-compose.yml, deployments/tyk/docker-compose.yml, deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf, deployments/tyk2/docker-compose.yml
Upgrade `tyk-demo` to use new release.  Gateway uses `3.2.1` as version `3.2.0` had a bug with Go/Python plugins, which were fixed in `3.2.1`
=> Upgrade versions

deployments/tyk/bootstrap.sh
Updating bootstrap.sh to support docker-compose v2.2.3 with -T flag.
=> Adding -T flag to bootstrap.sh for docker-compose v2.2.3 compatibility. 

deployments/portal/docker-compose.yml
Not all hosts support the `host.docker.internal` namespace.  Using the `tyk-dashboard` service name instead
=> Use the dashboard hostname instead of docker host hack

.gitignore, scripts/common.sh
1. Give access to mongo with a mongo client - Update command script with `tyk-mongo` so it's in `/etc/hosts`.
2. Update `.gitignore` to match the new plugin name format
=> Added tyk-mongo to /etc/hosts

deployments/tyk/data/tyk-dashboard/1/apis/api-60b8d132cd45340001bec761.json, deployments/tyk/tyk_demo_tyk.postman_collection.json, deployments/tyk/volumes/tyk-gateway/plugins/go/example/example-go-plugin.go
Adds example of a Go plugin that passes data between different hooks, and also executes as part of the response.
=> Plugin request response share data

scripts/common.sh
Updated common.sh to check underlying architecture and call plugin-compiler with `--platform`, `GOOS` and `GOARCH` set such that it builds plugins for ARM and AMD machines without issues.
=> Enable plugin-complier to build arm64 compatible go plugins

deployments/tyk/README.md, deployments/tyk/data/tyk-dashboard/1/apis/api-60b4968df312ae0001e1ad0d.json, deployments/tyk/data/tyk-dashboard/1/apis/api-60b8d132cd45340001bec761.json, deployments/tyk/volumes/tyk-gateway/plugins/go/example/example-go-plugin.go
[Issue 188](https://github.com/TykTechnologies/tyk-demo/issues/188)
Added new analytics function which masks response data to `example-go-plugin.go` and enabled on existing `Go Plugin API` and `Go Plugin API (No Auth)`
=> Added analytics function to existing example go plugin

deployments/subscriptions/Dockerfile, deployments/subscriptions/README.md, deployments/subscriptions/bootstrap.sh, deployments/subscriptions/data/apis-chatapp.json, deployments/subscriptions/docker-compose.yml
This PR adds a GraphQL subscriptions deployment that contains an example chat application from `graphql-go-tools`.
It also automatically adds a GraphQL proxy-only API for the chat app.
As exporting WebSocket Postman collection doesn't work I had to add the instructions to the readme (until the feature is implemented in postman).
=> add subscriptions deployment

deployments/mdcb/volumes/tyk-worker-gateway/tyk.conf
The worker gateway for MDCB setups has TYK_GW_USEDBAPPCONFIGS config set to true, which is a misconfiguration https://tyk.io/docs/tyk-oss-gateway/configuration/#use_db_app_configs
=> Update tyk.conf for worker gateway

deployments/analytics-kibana/volumes/tyk-pump/pump-elasticsearch.conf
Configuring extended_stats to true in order to capture raw request and raw response in elastic.
=> Setting elasticsearch pump configuration value extended_stats to true.

deployments/tracing/README.md, deployments/tracing/bootstrap.sh
as our OpenTracing support is deprecated and will be removed at some point, I have added an information to the OpenTracing/zipkin deployment. We don't need to update zipkin deployment with OpenTelemetry as Jaeger has become the most favourite open source tool for distributed tracing.
=> Adding deprecation notice for OpenTracing

deployments/cicd/scripts/dump-gitea.sh, deployments/mdcb/scripts/start-mdcb.sh, deployments/mdcb/scripts/stop-mdcb.sh, docker-compose-command.sh, down.sh, scripts/common.sh, up.sh
This resolves a problem with usage of the legacy `docker-compose` command. It's now time to force usage of `docker compose` instead.
=> Deprecate docker compose v1 support

scripts/common.sh
Resolves issue with licence_days_remaining not being global, which prevented the correct amount of days from being displayed on the terminal output.
=> allow licence_days_remaining to be global

deployments/tyk/bootstrap.sh, scripts/common.sh, scripts/test-common.sh, scripts/test.sh
fixes for testing and licence variations
=> Streams checks

deployments/tyk/docker-compose.yml
Instead of changing the port, we will just remove it. This service (and the other modified) do not need to be accessed from the host, since the gateway proxies requests to them instead.
=> remove unnecessary port mappings

deployments/tyk/data/tyk-dashboard/1/apis/api-8ba9f26729e041a95f84f01dd0ce6d9b.json
fix cors on gql in dev portal.  without these configs on the api def, the gql portal fails to fetch the schema from gql through tyk
=> fix cors on gql in dev portal
