TykTechnologies/tyk-demo

- deployments/tyk/data/tyk-dashboard/apis.json
- deployments/tyk/data/tyk-dashboard/policies.json
- deployments/tyk/docker-compose.yml
…,made the Petstore API require authToken, and exposed redis and mongo ports in docker-compose
> Fixed issue with empty Portal catalog

- up.sh
To get the full command printed
> Moved echo to get the pull command

- deployments/tyk/data/tyk-dashboard/apis.json
- deployments/tyk/data/tyk-dashboard/policies.json
- tyk_demo.postman_collection.json
Examples for GraphQL and UDG.
Closes #50
> GraphQL and UDG examples

- deployments/mdcb/docker-compose.yml
- deployments/sso/docker-compose.yml
- deployments/tyk/data/tyk-dashboard/apis.json
- deployments/tyk/data/tyk-dashboard/policies.json
- deployments/tyk/docker-compose.yml
- deployments/tyk2/docker-compose.yml
v3.0.1
plus fixes for missing policy data
> Version bump

- deployments/tyk2/docker-compose.yml
> Tyk env 2 env config changes

- deployments/tyk/data/tyk-dashboard/apis.json
- tyk_demo.postman_collection.json
Created a new API to demonstrate GraphQL capabilities. Have also added the corresponding Postman tests.
> Graphql posts

- deployments/mdcb/bootstrap.sh
- deployments/tyk/bootstrap.sh
- scripts/common.sh
- up.sh
Added checks for Dash and MDCB licence.
> Licence check

- deployments/tyk/docker-compose.yml
- deployments/tyk2/docker-compose.yml
Fixing the env variable in tyk2 dashboard and updating the new backup pinned tags for docker images
> Fixing Env Variable + Update Pinned Backup tags

- deployments/tyk/README.md
- deployments/tyk/data/tyk-dashboard/apis.json
- deployments/tyk/volumes/http-server/websocket-test.html
Basic WebSocket example.
Since Postman doesn't support WS, I created a test HTML page which can be used to demonstrate the functionality. This is covered in the update to the readme.
> WebSocket example

- deployments/tyk/docker-compose.yml
> Reinstate tracing env var

- deployments/analytics-kibana/README.md
- deployments/mdcb/docker-compose.yml
- deployments/tyk/docker-compose.yml
- deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf
- deployments/tyk/volumes/tyk-gateway/tyk.conf
- deployments/tyk2/docker-compose.yml
- scripts/add-gateway.sh
1. Updated the docker repo to use the new one. Tested and it's okay.
2. Change the default fields for key listing or update to true. MAkes sense since it's for demoing purposes. 
3. URL in the readme was 404ing
> A few updates: keys config, docker repo, kibana readme url

- deployments/mdcb/bootstrap.sh
- deployments/mdcb/docker-compose.yml
- deployments/tyk/bootstrap.sh
- deployments/tyk/docker-compose.yml
- deployments/tyk2/bootstrap.sh
- deployments/tyk2/docker-compose.yml
- scripts/add-gateway.sh
Also added the header name in the output since I am never sure if I mistype it when using the GW's apis
> Revert back to docker-hub

- deployments/ngrok/README.md
- deployments/ngrok/bootstrap.sh
- deployments/ngrok/docker-compose.yml
Added `wernight` container for ngrok with bootstrap script and instructions
> Add ngrok container to give external access to your environment

- deployments/analytics-kibana/README.md
- deployments/analytics-kibana/docker-compose.yml
Updating version of pump for kibana deployment, adding note on resource allocation.
> Update pump version of analytics-kibana deployment to 1.5.1

- deployments/analytics-splunk/bootstrap.sh
- deployments/analytics-splunk/docker-compose.yml
- deployments/analytics-splunk/volumes/tyk-pump/splunk-pump.conf
Adding ability to auto-populate splunk token so analytics properly show up.
> Updating splunk pump version. Fix splunk bootstrap so analytics work without needing a restart.

- deployments/federation/README.md
- deployments/federation/bootstrap.sh
- deployments/federation/data/apis-notifications.json
- deployments/federation/data/apis-posts.json
- deployments/federation/data/apis-users.json
- deployments/federation/docker-compose.yml
- deployments/federation/tyk_demo_federation.postman_collection.json
Update federation demo library.
> Update Federation lib

- deployments/slo-prometheus-grafana/README.md
- deployments/slo-prometheus-grafana/bootstrap.sh
- deployments/slo-prometheus-grafana/data/apis/httpbin.json
- deployments/slo-prometheus-grafana/data/apis/httpstatus.json
- deployments/slo-prometheus-grafana/docker-compose.yml
- deployments/slo-prometheus-grafana/volumes/grafana/dashboards/SLOs-for-APIs-managed-by-Tyk.json
- deployments/slo-prometheus-grafana/volumes/grafana/dashboards/dashboard.yml
- deployments/slo-prometheus-grafana/volumes/grafana/datasources/prometheus_ds.yml
- deployments/slo-prometheus-grafana/volumes/k6/load.js
- deployments/slo-prometheus-grafana/volumes/prometheus/prometheus.yml
- deployments/slo-prometheus-grafana/volumes/prometheus/slos.rules.yml
- deployments/slo-prometheus-grafana/volumes/tyk-pump/pump.conf
Ported across from [demo-slo-prometheus-grafana](https://github.com/TykTechnologies/demo-slo-prometheus-grafana).  Changes made to avoid port collisions and also modified the directory structure to fall inline with Tyk Demo standards
> Ported Prometheus/Grafana SLO Demo

- .github/workflows/tyk-demo-tests.yml
- deployments/tyk/bootstrap.sh
- deployments/tyk/data/tyk-dashboard/1/apis/api-5ead711f575961000181867a.json
- deployments/tyk/tyk_demo.postman_collection.json
Added some examples for context variables.
> add examples for context variables

- .github/workflows/tyk-demo-tests.yml
- .gitignore
- deployments/mdcb/README.md
- deployments/mdcb/bootstrap.sh
- deployments/mdcb/docker-compose.yml
- deployments/mdcb/tyk_demo_mdcb.postman_collection.json
- deployments/waf/docker-compose.yml
- deployments/waf/tyk_demo_waf.postman_collection.json
- scripts/test-all.sh
- up.sh
This branch uses the `test-all.sh` script to check for errors in all deployments that have postman collections that contain tests.
Updates the github action to use this script too.
I have noticed that tests will sometimes fail, presumable due to some environmental or race condition. But on a rerun, the test will pass. I think that since these are integration type tests, there will always be a risk of this type of failure.
> Test all GitHub action

- deployments/tyk/bootstrap.sh
- scripts/common.sh
> report negative licence days as error

- .github/workflows/tyk-demo-tests.yml
- .gitignore
- README.md
- deployments/analytics-kibana/bootstrap.sh
- deployments/analytics-splunk/bootstrap.sh
- deployments/cicd/bootstrap.sh
- deployments/database-postgres/bootstrap.sh
- deployments/mdcb/bootstrap.sh
- deployments/sso/bootstrap.sh
- deployments/tyk/bootstrap.sh
- deployments/tyk/docker-compose.yml
- deployments/tyk2/bootstrap.sh
- scripts/common.sh
- scripts/test-all.sh
- up.sh
Resolve race conditions that cause tests to fail
> Test logging

- .github/workflows/linters.yaml
- .github/workflows/tyk-demo-tests.yml
- .yamllint.yaml
- deployments/analytics-datadog/docker-compose.yml
- deployments/analytics-kibana/docker-compose.yml
- deployments/analytics-splunk/docker-compose.yml
- deployments/bench/docker-compose.yml
- deployments/cicd/docker-compose.yml
- deployments/database-postgres/docker-compose.yml
- deployments/federation/docker-compose.yml
- deployments/instrumentation/docker-compose.yml
- deployments/keycloak-dcr/docker-compose.yml
- deployments/mailserver/docker-compose.yml
- deployments/mdcb/docker-compose.yml
- deployments/mqtt/docker-compose.yml
- deployments/otel/docker-compose.yml
- deployments/otel/volumes/otel-collector.yml
- deployments/portal/docker-compose.yml
- deployments/slo-prometheus-grafana/docker-compose.yml
- deployments/slo-prometheus-grafana/volumes/grafana/dashboards/dashboard.yml
- deployments/slo-prometheus-grafana/volumes/grafana/datasources/prometheus_ds.yml
- deployments/slo-prometheus-grafana/volumes/prometheus/prometheus.yml
- deployments/slo-prometheus-grafana/volumes/prometheus/slos.rules.yml
- deployments/sso/docker-compose.yml
- deployments/tracing/docker-compose.yml
- deployments/tyk/docker-compose.yml
- deployments/tyk/volumes/ngrok/ngrok.yml
- deployments/tyk2/docker-compose.yml
- deployments/waf/docker-compose.yml
Change adds yamllint linter for validating yaml definitions.
#tykretreat2023 #greece2023
> Add yamllint to github workflows

- deployments/analytics-datadog/docker-compose.yml
- deployments/analytics-kibana/docker-compose.yml
- deployments/analytics-splunk/docker-compose.yml
- deployments/mdcb/docker-compose.yml
- deployments/slo-prometheus-grafana/docker-compose.yml
- deployments/sso/docker-compose.yml
- deployments/tyk/docker-compose.yml
- deployments/tyk2/docker-compose.yml
> Test 5.2.1 release

- deployments/tyk/README.md
- deployments/tyk/bootstrap.sh
- deployments/tyk/data/tyk-dashboard/1/apis/api-658407d6d211770001d76011.json
- deployments/tyk/data/tyk-dashboard/1/policies/policy-641c15dd0fffb800010197bf.json
- deployments/tyk/docker-compose.yml
- deployments/tyk/tyk_demo_tyk.postman_collection.json
Refactor to handle Ngrok failures gracefully:
- allow the bootstrap to complete
- avoid test failures if Ngrok is not available
> Ngrok refactor

- deployments/mdcb/docker-compose.yml
- deployments/sso/docker-compose.yml
- deployments/tyk/docker-compose.yml
- deployments/tyk2/docker-compose.yml
- scripts/add-gateway.sh
latest releases of:
- gateway / dashboard: 5.2.5
- mdcb: 2.4.1
> update to 5.2.5

- deployments/tyk/README.md
Fixed broken link of analytics plugin
> Update Readme of tyk deployment

- .gitignore
- scripts/update-licence.sh
example:
`./scripts/update-licence.sh my-licence-key`
> License update script, instead of editing

- deployments/cicd/scripts/dump-tyk.sh
- deployments/load-balancer-nginx/docker-compose.yml
- deployments/mdcb/docker-compose.yml
- deployments/plugin-python-grpc/docker-compose.yml
- deployments/sso/docker-compose.yml
- deployments/tyk/docker-compose.yml
- deployments/tyk2/docker-compose.yml
- scripts/add-gateway.sh
Gateway & Dashboard v5.3.2
MDCB v2.5.1
Operator v0.17
Sync v1.4.3
Enterprise Developer Portal v1.8.3
Pump v1.9.0
Identity Broker v1.5.1
> update to 5.3.2 release images

- deployments/plugin-python-grpc/docker-compose.yml
- deployments/sso/bootstrap.sh
- deployments/sso/docker-compose.yml
Bump gateway and dash images that were missed in previous update. 
Plus a small fix for SSO deployment.
> V5.4.0 others

- deployments/tyk/data/tyk-dashboard/1/apis/api-66a7b522b1d7890001c3b040.json
- deployments/tyk/data/tyk-dashboard/1/apis/api-66a7b7fdb1d7890001c3b041.json
- deployments/tyk/docker-compose.yml
- deployments/tyk/scripts/examples/gRPC-api.sh
Adds an example gRPC service and Tyk API definition, along with an example script that makes gRPC requests via the gateway
> gRPC example

- deployments/tyk/bootstrap.sh
Resolve issue with empty value displayed
> display 'not configured' when no config is present

- deployments/portal-backstage/Dockerfile
resolve issue seemingly related to running this deployment on arm architecture
> install python into image, so node-gyp can use it

- deployments/load-balancer-nginx/docker-compose.yml
- deployments/mdcb/docker-compose.yml
- deployments/sso/docker-compose.yml
- deployments/tyk/data/tyk-dashboard/1/apis/api-727dad853a8a45f64ab981154d1ffdad.json
- deployments/tyk/data/tyk-dashboard/1/apis/api-7d29ac67565045706a2209ab647ef22a.json
- deployments/tyk/data/tyk-dashboard/1/apis/api-d0ab4e97086e4ee865179d3824b816f4.json
- deployments/tyk/data/tyk-dashboard/1/apis/api-oas-b84fe1a04e5648927971c0557971565c.json
- deployments/tyk/data/tyk-dashboard/1/apis/api-oas-f96f64e3ab82435a541d3de7a6c5ad89.json
- deployments/tyk/docker-compose.yml
- deployments/tyk/scripts/examples/dynamic-client-mtls.sh
- deployments/tyk/tyk_demo_tyk.postman_collection.json
- deployments/tyk/volumes/tyk-gateway/tyk-2.conf
- deployments/tyk/volumes/tyk-gateway/tyk.conf
- deployments/tyk2/docker-compose.yml
- scripts/add-gateway.sh
Updates for the product changes for URL matching and strict routes
> Security options

- deployments/analytics-splunk/bootstrap.sh
- deployments/analytics-splunk/docker-compose.yml
support splunk on arm64 via rosetta emulation
> Splunk arm64

- deployments/portal-backstage/Dockerfile
resolves compatibility issue between node and backstage
> bump node version

- deployments/tyk/data/tyk-dashboard/1/apis/api-oas-146f887972a944dd72facb9653d2b76c.json
- deployments/tyk/tyk_demo_tyk.postman_collection.json
Using regex to allow a single api def to match against multiple particular listen paths
> Multi listen paths

- deployments/tyk/bootstrap.sh
- scripts/test-all.sh
- up.sh
add ability to skip building plugins
> Skip plugins

- scripts/update-hosts.sh
Previously, the script wasn't reading the last line because there wasn't a `/n` character.  Modified the script to read the last line.
> Fix the script to read the last line in the hosts list
